# -*- coding: utf-8 -*-
"""CharRNN_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F3Gnk8N8wUz8iAGdBNvd-5GsNR06wWXT
"""





"""
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import random
from torch.utils.data import TensorDataset, DataLoader


# ============================================================
# 2. SET RANDOM SEEDS
# ============================================================

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)


# ============================================================
# 3. DEVICE
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", device)


# ============================================================
# 4. BASELINE HYPERPARAMETERS
# ============================================================

embedding_size = 64
hidden_size = 128
num_layers = 1
seq_length = 50
batch_size = 64
learning_rate = 0.001
dropout = 0.0
epochs = 20


print("\n" + "=" * 50)
print("BASELINE HYPERPARAMETERS")
print("=" * 50)

print(f"Embedding Size:       {embedding_size}")
print(f"Hidden Size:          {hidden_size}")
print(f"Number of RNN Layers: {num_layers}")
print(f"Sequence Length:      {seq_length}")
print(f"Batch Size:           {batch_size}")
print(f"Learning Rate:        {learning_rate}")
print("Optimizer:            Adam")
print(f"Dropout:              {dropout}")
print(f"Epochs:               {epochs}")

print("=" * 50)


# ============================================================
# 5. LOAD DATASET
# ============================================================

dataset = "/content/sample_data/TomJones.txt"

with open(
    dataset,
    "r",
    encoding="utf-8"
) as f:

    full_text = f.read()


print("\nCorpus length:", len(full_text))


# ============================================================
# 6. CHARACTER TOKENIZER
# ============================================================

class CharacterTokenizer:

    def __init__(self, text):

        self.chars = sorted(
            list(set(text))
        )

        self.vocab_size = len(
            self.chars
        )

        self.char_to_idx = {
            ch: i
            for i, ch in enumerate(self.chars)
        }

        self.idx_to_char = {
            i: ch
            for i, ch in enumerate(self.chars)
        }


    def encode(self, text):

        return [
            self.char_to_idx[ch]
            for ch in text
        ]


    def decode(self, indices):

        return ''.join(
            self.idx_to_char[i]
            for i in indices
        )


tokenizer = CharacterTokenizer(
    full_text
)


print(
    "Vocabulary size:",
    tokenizer.vocab_size
)


# ============================================================
# 7. CREATE CHARACTER SEQUENCES
# ============================================================

def create_sequences(
    text,
    seq_length
):

    encoded = tokenizer.encode(
        text
    )

    sequences = []
    targets = []

    for i in range(
        len(encoded) - seq_length
    ):

        sequences.append(
            encoded[
                i:i + seq_length
            ]
        )

        targets.append(
            encoded[
                i + seq_length
            ]
        )


    return (
        torch.tensor(
            sequences,
            dtype=torch.long
        ),
        torch.tensor(
            targets,
            dtype=torch.long
        )
    )


X, y = create_sequences(
    full_text,
    seq_length
)


print(
    "Total sequences:",
    len(X)
)


# ============================================================
# 8. TRAINING / VALIDATION SPLIT
# ============================================================

split = int(
    0.9 * len(X)
)


# 90% training data

train_data = TensorDataset(
    X[:split],
    y[:split]
)


# 10% validation data

val_data = TensorDataset(
    X[split:],
    y[split:]
)


print(
    "Training sequences:",
    len(train_data)
)

print(
    "Validation sequences:",
    len(val_data)
)


# ============================================================
# 9. DATA LOADERS
# ============================================================

train_loader = DataLoader(
    train_data,
    batch_size=batch_size,
    shuffle=True
)


val_loader = DataLoader(
    val_data,
    batch_size=batch_size,
    shuffle=False
)


print(
    "Training batches per epoch:",
    len(train_loader)
)

print(
    "Validation batches per epoch:",
    len(val_loader)
)


# ============================================================
# 10. CHARACTER RNN MODEL
# ============================================================

class CharRNN(nn.Module):

    def __init__(
        self,
        vocab_size,
        embedding_size,
        hidden_size,
        num_layers,
        dropout
    ):

        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers


        # ----------------------------------------------------
        # Embedding layer
        # ----------------------------------------------------

        self.embedding = nn.Embedding(
            vocab_size,
            embedding_size
        )


        # ----------------------------------------------------
        # GRU recurrent layer
        # ----------------------------------------------------

        self.rnn = nn.GRU(
            input_size=embedding_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,

            # PyTorch applies GRU dropout between layers.
            # Since baseline uses one layer, dropout is 0.
            dropout=(
                dropout
                if num_layers > 1
                else 0.0
            )
        )


        # ----------------------------------------------------
        # Output layer
        # ----------------------------------------------------

        self.fc = nn.Linear(
            hidden_size,
            vocab_size
        )


    def forward(
        self,
        x,
        hidden=None
    ):

        # ----------------------------------------------------
        # Initialize hidden state
        # ----------------------------------------------------

        if hidden is None:

            hidden = torch.zeros(
                self.num_layers,
                x.size(0),
                self.hidden_size,
                device=x.device
            )


        # ----------------------------------------------------
        # Character embeddings
        # ----------------------------------------------------

        x = self.embedding(x)


        # ----------------------------------------------------
        # GRU
        # ----------------------------------------------------

        output, hidden = self.rnn(
            x,
            hidden
        )


        # ----------------------------------------------------
        # Output predictions
        # ----------------------------------------------------

        output = self.fc(
            output
        )


        return output, hidden


# ============================================================
# 11. CREATE MODEL
# ============================================================

model = CharRNN(
    vocab_size=tokenizer.vocab_size,
    embedding_size=embedding_size,
    hidden_size=hidden_size,
    num_layers=num_layers,
    dropout=dropout
).to(device)


print("\nMODEL")
print(model)


# ============================================================
# 12. LOSS FUNCTION
# ============================================================

criterion = nn.CrossEntropyLoss()


# ============================================================
# 13. OPTIMIZER
# ============================================================

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)


# ============================================================
# 14. LOSS STORAGE
# ============================================================

training_losses = []
validation_losses = []


# ============================================================
# 15. TRAINING + VALIDATION LOOP
# ============================================================

for epoch in range(epochs):

    # ========================================================
    # TRAINING
    # ========================================================

    model.train()

    total_train_loss = 0.0


    train_progress = tqdm(
        train_loader,
        desc=f"Epoch {epoch + 1}/{epochs}"
    )


    for inputs, targets in train_progress:

        # Move data to device

        inputs = inputs.to(
            device
        )

        targets = targets.to(
            device
        )


        # Clear previous gradients

        optimizer.zero_grad()


        # Forward pass

        output, _ = model(
            inputs
        )


        # Calculate training loss

        loss = criterion(
            output[:, -1, :],
            targets
        )


        # Backpropagation

        loss.backward()


        # Gradient clipping

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=5
        )


        # Update weights

        optimizer.step()


        # Add batch loss

        total_train_loss += (
            loss.item()
        )


        # Show current batch loss

        train_progress.set_postfix(
            loss=f"{loss.item():.4f}"
        )


    # ========================================================
    # CALCULATE AVERAGE TRAINING LOSS
    # ========================================================

    avg_train_loss = (
        total_train_loss /
        len(train_loader)
    )


    training_losses.append(
        avg_train_loss
    )


    # ========================================================
    # VALIDATION
    # ========================================================

    model.eval()

    total_val_loss = 0.0


    # Turn off gradient calculation

    with torch.no_grad():

        for inputs, targets in val_loader:

            inputs = inputs.to(
                device
            )

            targets = targets.to(
                device
            )


            # Forward pass

            output, _ = model(
                inputs
            )


            # Calculate validation loss

            val_loss = criterion(
                output[:, -1, :],
                targets
            )


            total_val_loss += (
                val_loss.item()
            )


    # ========================================================
    # CALCULATE AVERAGE VALIDATION LOSS
    # ========================================================

    avg_val_loss = (
        total_val_loss /
        len(val_loader)
    )


    validation_losses.append(
        avg_val_loss
    )


    # ========================================================
    # PRINT EPOCH RESULTS
    # ========================================================

    print(
        f"\nEpoch {epoch + 1}/{epochs}"
    )

    print(
        f"Training Loss:   "
        f"{avg_train_loss:.4f}"
    )

    print(
        f"Validation Loss: "
        f"{avg_val_loss:.4f}"
    )

    print("-" * 40)


# ============================================================
# 16. TRAINING + VALIDATION LOSS TABLE
# ============================================================

print(
    "\nTRAINING AND VALIDATION LOSS TABLE"
)

print("=" * 60)


print(
    f"{'Epoch':<10}"
    f"{'Training Loss':<20}"
    f"{'Validation Loss':<20}"
)


print("-" * 60)


for i in range(epochs):

    print(
        f"{i + 1:<10}"
        f"{training_losses[i]:<20.4f}"
        f"{validation_losses[i]:<20.4f}"
    )


print("=" * 60)


# ============================================================
# 17. EPOCH NUMBERS
# ============================================================

epoch_numbers = list(
    range(
        1,
        epochs + 1
    )
)


# ============================================================
# 18. GRAPH 1
# TRAINING LOSS + VALIDATION LOSS
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    training_losses,
    marker="o",
    linewidth=2,
    label="Training Loss"
)


plt.plot(
    epoch_numbers,
    validation_losses,
    marker="s",
    linewidth=2,
    label="Validation Loss"
)


plt.title(
    "Training and Validation Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Loss"
)


plt.xticks(
    epoch_numbers
)


plt.legend()


plt.grid(
    True
)


plt.tight_layout()


plt.show()


# ============================================================
# 19. GRAPH 2
# TRAINING LOSS VS. EPOCH
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    training_losses,
    marker="o",
    linewidth=2
)


plt.title(
    "Training Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Training Loss"
)


plt.xticks(
    epoch_numbers
)


plt.grid(
    True
)


plt.tight_layout()


plt.show()


# ============================================================
# 20. GRAPH 3
# VALIDATION LOSS VS. EPOCH
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    validation_losses,
    marker="o",
    linewidth=2
)


plt.title(
    "Validation Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Validation Loss"
)


plt.xticks(
    epoch_numbers
)


plt.grid(
    True
)


plt.tight_layout()


plt.show()


# ============================================================
# 21. TEXT GENERATION FUNCTION
# ============================================================

def generate_text(
    seed_text,
    length=500,
    temperature=1.0
):

    model.eval()

    generated = seed_text

    current = seed_text


    # --------------------------------------------------------
    # Make sure seed characters exist in vocabulary
    # --------------------------------------------------------

    valid_seed = ''.join(
        ch for ch in current
        if ch in tokenizer.char_to_idx
    )


    if len(valid_seed) == 0:

        raise ValueError(
            "Seed text contains no characters "
            "from the training vocabulary."
        )


    current = valid_seed
    generated = valid_seed


    # --------------------------------------------------------
    # Convert seed into tensor
    # --------------------------------------------------------

    x = torch.tensor(
        [
            tokenizer.encode(
                current
            )
        ],
        dtype=torch.long
    ).to(device)


    hidden = None


    # --------------------------------------------------------
    # Generate characters
    # --------------------------------------------------------

    with torch.no_grad():

        for _ in range(length):

            output, hidden = model(
                x,
                hidden
            )


            # Get prediction from
            # the last position

            output = (
                output[:, -1, :] /
                temperature
            )


            # Convert logits to probabilities

            probabilities = F.softmax(
                output,
                dim=1
            )


            # Sample next character

            next_idx = torch.multinomial(
                probabilities,
                1
            ).item()


            # Decode character

            next_char = tokenizer.decode(
                [next_idx]
            )


            # Add generated character

            generated += next_char


            # Keep latest characters

            current = (
                current + next_char
            )[-seq_length:]


            # Create next input

            x = torch.tensor(
                [
                    tokenizer.encode(
                        current
                    )
                ],
                dtype=torch.long
            ).to(device)


            # Reset hidden state because
            # the complete current sequence
            # is being fed into the model again.

            hidden = None


    return generated


# ============================================================
# 22. GENERATE SAMPLE TEXT
# ============================================================

print(
    "\nGENERATED TEXT: PROMPT 1"
)

print("=" * 60)

#Prompt 1
generated_text = generate_text(
    seed_text="Once upon a time",
    length=500,
    temperature=0.8
)


print(
    generated_text
)

print(
    "\nGENERATED TEXT: PROMPT 2"
)

print("=" * 60)


#Prompt 2
generated_text = generate_text(
    seed_text="My name is Al",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 3
print(
    "\nGENERATED TEXT: PROMPT 3"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="Hell",
    length=500,
    temperature=0.8
)

print(
    generated_text
)


"""
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import random
import time

from torch.utils.data import TensorDataset, DataLoader


# ============================================================
# 2. SET RANDOM SEEDS
# ============================================================

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)


# ============================================================
# 3. DEVICE
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", device)


# ============================================================
# 4. BASELINE HYPERPARAMETERS
# ============================================================

embedding_size = 64
hidden_size = 64
num_layers = 3
seq_length = 100
batch_size = 64
learning_rate = 0.0001
dropout = 0.3
epochs = 13


print("\n" + "=" * 50)
print("BASELINE HYPERPARAMETERS")
print("=" * 50)

print(f"Embedding Size:       {embedding_size}")
print(f"Hidden Size:          {hidden_size}")
print(f"Number of RNN Layers: {num_layers}")
print(f"Sequence Length:      {seq_length}")
print(f"Batch Size:           {batch_size}")
print(f"Learning Rate:        {learning_rate}")
print("Optimizer:            Adam")
print(f"Dropout:              {dropout}")
print(f"Epochs:               {epochs}")

print("=" * 50)



# ============================================================
# 5. LOAD DATASET
# ============================================================

dataset = "/content/sample_data/TomJones.txt"

with open(
    dataset,
    "r",
    encoding="utf-8"
) as f:

    full_text = f.read()


print("\nCorpus length:", len(full_text))


# ============================================================
# 6. CHARACTER TOKENIZER
# ============================================================

class CharacterTokenizer:

    def __init__(self, text):

        self.chars = sorted(
            list(set(text))
        )

        self.vocab_size = len(
            self.chars
        )

        self.char_to_idx = {
            ch: i
            for i, ch in enumerate(self.chars)
        }

        self.idx_to_char = {
            i: ch
            for i, ch in enumerate(self.chars)
        }


    def encode(self, text):

        return [
            self.char_to_idx[ch]
            for ch in text
        ]


    def decode(self, indices):

        return ''.join(
            self.idx_to_char[i]
            for i in indices
        )


tokenizer = CharacterTokenizer(
    full_text
)


print(
    "Vocabulary size:",
    tokenizer.vocab_size
)


# ============================================================
# 7. CREATE CHARACTER SEQUENCES
# ============================================================

def create_sequences(
    text,
    seq_length
):

    encoded = tokenizer.encode(
        text
    )

    sequences = []
    targets = []

    for i in range(
        len(encoded) - seq_length
    ):

        sequences.append(
            encoded[
                i:i + seq_length
            ]
        )

        targets.append(
            encoded[
                i + seq_length
            ]
        )


    return (
        torch.tensor(
            sequences,
            dtype=torch.long
        ),
        torch.tensor(
            targets,
            dtype=torch.long
        )
    )


X, y = create_sequences(
    full_text,
    seq_length
)


print(
    "Total sequences:",
    len(X)
)


# ============================================================
# 8. TRAINING / VALIDATION SPLIT
# ============================================================

split = int(
    0.9 * len(X)
)


# 90% training data

train_data = TensorDataset(
    X[:split],
    y[:split]
)


# 10% validation data

val_data = TensorDataset(
    X[split:],
    y[split:]
)


print(
    "Training sequences:",
    len(train_data)
)

print(
    "Validation sequences:",
    len(val_data)
)


# ============================================================
# 9. DATA LOADERS
# ============================================================

train_loader = DataLoader(
    train_data,
    batch_size=batch_size,
    shuffle=True
)


val_loader = DataLoader(
    val_data,
    batch_size=batch_size,
    shuffle=False
)


print(
    "Training batches per epoch:",
    len(train_loader)
)

print(
    "Validation batches per epoch:",
    len(val_loader)
)


# ============================================================
# 10. CHARACTER RNN MODEL
# ============================================================

class CharRNN(nn.Module):

    def __init__(
        self,
        vocab_size,
        embedding_size,
        hidden_size,
        num_layers,
        dropout
    ):

        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers


        # ----------------------------------------------------
        # Embedding layer
        # ----------------------------------------------------

        self.embedding = nn.Embedding(
            vocab_size,
            embedding_size
        )


        # ----------------------------------------------------
        # GRU recurrent layer
        # ----------------------------------------------------

        self.rnn = nn.GRU(
            input_size=embedding_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,

            # PyTorch applies GRU dropout between layers.
            # Since baseline uses one layer, dropout is 0.
            dropout=(
                dropout
                if num_layers > 1
                else 0.0
            )
        )


        # ----------------------------------------------------
        # Output layer
        # ----------------------------------------------------

        self.fc = nn.Linear(
            hidden_size,
            vocab_size
        )


    def forward(
        self,
        x,
        hidden=None
    ):

        # ----------------------------------------------------
        # Initialize hidden state
        # ----------------------------------------------------

        if hidden is None:

            hidden = torch.zeros(
                self.num_layers,
                x.size(0),
                self.hidden_size,
                device=x.device
            )


        # ----------------------------------------------------
        # Character embeddings
        # ----------------------------------------------------

        x = self.embedding(x)


        # ----------------------------------------------------
        # GRU
        # ----------------------------------------------------

        output, hidden = self.rnn(
            x,
            hidden
        )


        # ----------------------------------------------------
        # Output predictions
        # ----------------------------------------------------

        output = self.fc(
            output
        )


        return output, hidden


# ============================================================
# 11. CREATE MODEL
# ============================================================

model = CharRNN(
    vocab_size=tokenizer.vocab_size,
    embedding_size=embedding_size,
    hidden_size=hidden_size,
    num_layers=num_layers,
    dropout=dropout
).to(device)


print("\nMODEL")
print(model)


# ============================================================
# 12. LOSS FUNCTION
# ============================================================

criterion = nn.CrossEntropyLoss()


# ============================================================
# 13. OPTIMIZER
# ============================================================

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)


# ============================================================
# 14. LOSS STORAGE
# ============================================================

training_losses = []
validation_losses = []


# ============================================================
# 15. FINAL ACCURACY STORAGE
# ============================================================

final_train_accuracy = 0.0
final_val_accuracy = 0.0


# ============================================================
# 16. START TOTAL TRAINING TIMER
# ============================================================

training_start_time = time.perf_counter()


# ============================================================
# 17. TRAINING + VALIDATION LOOP
# ============================================================

for epoch in range(epochs):

    # ========================================================
    # TRAINING
    # ========================================================

    model.train()

    total_train_loss = 0.0

    # Accuracy counters
    train_correct = 0
    train_total = 0


    train_progress = tqdm(
        train_loader,
        desc=f"Epoch {epoch + 1}/{epochs}"
    )


    for inputs, targets in train_progress:

        # Move data to device

        inputs = inputs.to(
            device
        )

        targets = targets.to(
            device
        )


        # Clear previous gradients

        optimizer.zero_grad()


        # Forward pass

        output, _ = model(
            inputs
        )


        # Calculate training loss

        loss = criterion(
            output[:, -1, :],
            targets
        )


        # Backpropagation

        loss.backward()


        # Gradient clipping

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=5
        )


        # Update weights

        optimizer.step()


        # Add batch loss

        total_train_loss += (
            loss.item()
        )


        # ----------------------------------------------------
        # TRAINING ACCURACY
        # ----------------------------------------------------

        predictions = torch.argmax(
            output[:, -1, :],
            dim=1
        )

        train_correct += (
            predictions == targets
        ).sum().item()

        train_total += targets.size(0)


        # Show current batch loss

        train_progress.set_postfix(
            loss=f"{loss.item():.4f}"
        )


    # ========================================================
    # CALCULATE AVERAGE TRAINING LOSS
    # ========================================================

    avg_train_loss = (
        total_train_loss /
        len(train_loader)
    )


    training_losses.append(
        avg_train_loss
    )


    # ========================================================
    # CALCULATE TRAINING ACCURACY
    # ========================================================

    train_accuracy = (
        train_correct /
        train_total
    ) * 100


    # ========================================================
    # VALIDATION
    # ========================================================

    model.eval()

    total_val_loss = 0.0

    # Accuracy counters
    val_correct = 0
    val_total = 0


    # Turn off gradient calculation

    with torch.no_grad():

        for inputs, targets in val_loader:

            inputs = inputs.to(
                device
            )

            targets = targets.to(
                device
            )


            # Forward pass

            output, _ = model(
                inputs
            )


            # Calculate validation loss

            val_loss = criterion(
                output[:, -1, :],
                targets
            )


            total_val_loss += (
                val_loss.item()
            )


            # ------------------------------------------------
            # VALIDATION ACCURACY
            # ------------------------------------------------

            predictions = torch.argmax(
                output[:, -1, :],
                dim=1
            )

            val_correct += (
                predictions == targets
            ).sum().item()

            val_total += targets.size(0)


    # ========================================================
    # CALCULATE AVERAGE VALIDATION LOSS
    # ========================================================

    avg_val_loss = (
        total_val_loss /
        len(val_loader)
    )


    validation_losses.append(
        avg_val_loss
    )


    # ========================================================
    # CALCULATE VALIDATION ACCURACY
    # ========================================================

    val_accuracy = (
        val_correct /
        val_total
    ) * 100


    # Save current accuracies.
    # After epoch 20, these contain the final accuracies.

    final_train_accuracy = train_accuracy
    final_val_accuracy = val_accuracy


    # ========================================================
    # PRINT EPOCH LOSS RESULTS
    # ========================================================

    print(
        f"\nEpoch {epoch + 1}/{epochs}"
    )

    print(
        f"Training Loss:   "
        f"{avg_train_loss:.4f}"
    )

    print(
        f"Validation Loss: "
        f"{avg_val_loss:.4f}"
    )

    print("-" * 40)


# ============================================================
# 18. STOP TOTAL TRAINING TIMER
# ============================================================

training_end_time = time.perf_counter()

total_training_time = (
    training_end_time -
    training_start_time
)

training_minutes = int(
    total_training_time // 60
)

training_seconds = (
    total_training_time % 60
)


# ============================================================
# 19. PRINT FINAL ACCURACY + TOTAL TRAINING TIME
# ============================================================

print("\n" + "=" * 60)

print("FINAL MODEL RESULTS")

print("=" * 60)

print(
    f"Final Training Accuracy:   "
    f"{final_train_accuracy:.2f}%"
)

print(
    f"Final Validation Accuracy: "
    f"{final_val_accuracy:.2f}%"
)

print(
    f"Total Training Time:       "
    f"{training_minutes} min "
    f"{training_seconds:.2f} sec"
)

print("=" * 60)


# ============================================================
# 20. TRAINING + VALIDATION LOSS TABLE
# ============================================================

print(
    "\nTRAINING AND VALIDATION LOSS TABLE"
)

print("=" * 60)


print(
    f"{'Epoch':<10}"
    f"{'Training Loss':<20}"
    f"{'Validation Loss':<20}"
)


print("-" * 60)


for i in range(epochs):

    print(
        f"{i + 1:<10}"
        f"{training_losses[i]:<20.4f}"
        f"{validation_losses[i]:<20.4f}"
    )


print("=" * 60)


# ============================================================
# 21. EPOCH NUMBERS
# ============================================================

epoch_numbers = list(
    range(
        1,
        epochs + 1
    )
)


# ============================================================
# 22. GRAPH 1
# TRAINING LOSS + VALIDATION LOSS
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    training_losses,
    marker="o",
    linewidth=2,
    label="Training Loss"
)


plt.plot(
    epoch_numbers,
    validation_losses,
    marker="s",
    linewidth=2,
    label="Validation Loss"
)


plt.title(
    "Training and Validation Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Loss"
)


plt.xticks(
    epoch_numbers
)


plt.legend()


plt.grid(
    True
)


plt.tight_layout()


plt.show()


# ============================================================
# 23. GRAPH 2
# TRAINING LOSS VS. EPOCH
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    training_losses,
    marker="o",
    linewidth=2
)


plt.title(
    "Training Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Training Loss"
)


plt.xticks(
    epoch_numbers
)


plt.grid(
    True
)


plt.tight_layout()


plt.show()


# ============================================================
# 24. GRAPH 3
# VALIDATION LOSS VS. EPOCH
# ============================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(
    epoch_numbers,
    validation_losses,
    marker="o",
    linewidth=2
)


plt.title(
    "Validation Loss vs. Epoch"
)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Validation Loss"
)


plt.xticks(
    epoch_numbers
)


plt.grid(
    True
)


plt.tight_layout()


plt.show()

print ("Hyperparameter Tuning: Phase 2")
# ============================================================
# 25. TEXT GENERATION FUNCTION
# ============================================================

def generate_text(
    seed_text,
    length=500,
    temperature=1.0
):

    model.eval()

    generated = seed_text

    current = seed_text


    # --------------------------------------------------------
    # Make sure seed characters exist in vocabulary
    # --------------------------------------------------------

    valid_seed = ''.join(
        ch for ch in current
        if ch in tokenizer.char_to_idx
    )


    if len(valid_seed) == 0:

        raise ValueError(
            "Seed text contains no characters "
            "from the training vocabulary."
        )


    current = valid_seed
    generated = valid_seed


    # --------------------------------------------------------
    # Convert seed into tensor
    # --------------------------------------------------------

    x = torch.tensor(
        [
            tokenizer.encode(
                current
            )
        ],
        dtype=torch.long
    ).to(device)


    hidden = None


    # --------------------------------------------------------
    # Generate characters
    # --------------------------------------------------------

    with torch.no_grad():

        for _ in range(length):

            output, hidden = model(
                x,
                hidden
            )


            # Get prediction from
            # the last position

            output = (
                output[:, -1, :] /
                temperature
            )


            # Convert logits to probabilities

            probabilities = F.softmax(
                output,
                dim=1
            )


            # Sample next character

            next_idx = torch.multinomial(
                probabilities,
                1
            ).item()


            # Decode character

            next_char = tokenizer.decode(
                [next_idx]
            )


            # Add generated character

            generated += next_char


            # Keep latest characters

            current = (
                current + next_char
            )[-seq_length:]


            # Create next input

            x = torch.tensor(
                [
                    tokenizer.encode(
                        current
                    )
                ],
                dtype=torch.long
            ).to(device)


            # Reset hidden state because
            # the complete current sequence
            # is being fed into the model again.

            hidden = None


    return generated


# ============================================================
# 26. GENERATE SAMPLE TEXT
# ============================================================

print(
    "\nGENERATED TEXT"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="Hell",
    length=500,
    temperature=0.8
)


print(
    generated_text
)


#Prompt 2
print(
    "\nGENERATED TEXT: PROMPT 2"
)

print("=" * 60)



generated_text = generate_text(
    seed_text="It's important to always be kin",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 3
print(
    "\nGENERATED TEXT: PROMPT 3"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="I like cook",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 4
print(
    "\nGENERATED TEXT: PROMPT 4"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="Make good hab",
    length=500,
    temperature=0.8
)

print(
    generated_text
)


#Prompt 5
print(
    "\nGENERATED TEXT: PROMPT 5"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="I lov",
    length=500,
    temperature=0.8
)

print(
    generated_text
)


#Prompt 6
print(
    "\nGENERATED TEXT: PROMPT 6"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="My fri",
    length=500,
    temperature=0.8
)

print(
    generated_text
)


#Prompt 7
print(
    "\nGENERATED TEXT: PROMPT 7"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="I'm excit",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 8
print(
    "\nGENERATED TEXT: PROMPT 8"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="There are several row",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 9
print(
    "\nGENERATED TEXT: PROMPT 9"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="Down the roa",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

#Prompt 10
print(
    "\nGENERATED TEXT: PROMPT 10"
)

print("=" * 60)

generated_text = generate_text(
    seed_text="Education is freed",
    length=500,
    temperature=0.8
)

print(
    generated_text
)

from google.colab import drive
drive.mount('/content/drive')